version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: dica_postgres
    environment:
      POSTGRES_USER: acesso1
      POSTGRES_PASSWORD: acesso1tcc4323
      POSTGRES_DB: DicaBD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dica-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U acesso1 -d DicaBD"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama-ai:
    image: ollama/ollama:latest
    container_name: dica_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - dica-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  backend-api:
    build: .
    container_name: dica_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - ollama-ai
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=acesso1
      - SPRING_DATASOURCE_PASSWORD=acesso1tcc4323
      - JWT_SECRET=253245245
      - tz=America/Sao_Paulo
    networks:
      - dica-network

volumes:
  pgdata:
  ollama_data:

networks:
  dica-network:
    driver: bridge