spring.application.name=dica-br-api

spring.datasource.url=jdbc:postgresql://localhost:5432/DicaBD
spring.datasource.username=acessospring
spring.datasource.password=1232
spring.datasource.driver-class-name=org.postgresql.Driver


